apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-notifications-to-kubeapi
  namespace: argocd

spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller

  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP