apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: chatapp-alertmanager
  namespace: monitoring
  labels:
    release: monitoring

spec:
  route:
    receiver: gmail-warning

    groupBy:
      - alertname
      - namespace
      - component
      - severity

    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h

    routes:
      - receiver: gmail-critical
        matchers:
          - name: severity
            value: critical
        repeatInterval: 30m

      - receiver: gmail-warning
        matchers:
          - name: severity
            value: warning
        repeatInterval: 4h

  receivers:
    - name: gmail-warning
      emailConfigs:
        - to: "__EMAIL_TO__"
          from: "__EMAIL_FROM__"

          smarthost: smtp.gmail.com:587
          requireTLS: true
          sendResolved: true

          authUsername: "__SMTP_USERNAME__"

          authPassword:
            name: alertmanager-gmail
            key: password

          headers:
            - key: Subject
              value: '{{ template "chatapp.subject" . }}'

          text: '{{ template "chatapp.text" . }}'

    - name: gmail-critical
      emailConfigs:
        - to: "__EMAIL_TO__"
          from: "__EMAIL_FROM__"

          smarthost: smtp.gmail.com:587
          requireTLS: true
          sendResolved: true

          authUsername: "__SMTP_USERNAME__"

          authPassword:
            name: alertmanager-gmail
            key: password

          headers:
            - key: Subject
              value: '[CRITICAL] {{ template "chatapp.subject" . }}'

          text: '{{ template "chatapp.text" . }}'