apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: alertmanager-gmail
  namespace: monitoring

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: alertmanager-gmail
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: chatapp/monitoring/alertmanager/gmail
        property: username

    - secretKey: password
      remoteRef:
        key: chatapp/monitoring/alertmanager/gmail
        property: password