apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - front
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s