apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-controller-to-repo
  namespace: argocd

spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller

  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: argocd-repo-server
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP