apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allow-controller-to-repo.yaml
  - allow-controller-to-redis.yaml
  - allow-notifications-to-redis.yaml
  - allow-server-to-dex.yaml
  - allow-server-to-redis.yaml
  - allow-server-to-repo.yaml