apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-alertmanager-smtp-to-world
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: alertmanager

  egress:
    - toFQDNs:
        - matchName: smtp.gmail.com
      toPorts:
        - ports:
            - port: "587"
              protocol: TCP