apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: frontend
  namespace: argocd

spec:
  project: prod

  source:
    repoURL: https://github.com/rajarshigit2441139/full-stack_chatApp.git
    targetRevision: k8s
    path: k8s/deploy/frontend/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: front

  syncPolicy:
    automated:
      prune: true
      selfHeal: true