apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cluster-setup
  namespace: argocd

spec:
  project: platform-staging

  source:
    repoURL: https://github.com/rajarshigit2441139/full-stack_chatApp.git
    targetRevision: k8s
    path: k8s/gitops/10-cluster-setup/overlays/staging

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true