replicaCount: 1

nodeSelector:
  node-role.kubernetes.io/control-plane: ""

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

webhook:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

certController:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule