grafana:
  service:
    type: NodePort
    nodePort: 30000

  nodeSelector:
    app: monitoring

  tolerations:
    - key: app
      value: monitoring
      operator: Equal

prometheus:
  service:
    type: NodePort
    nodePort: 30900

  prometheusSpec:
    nodeSelector:
      app: monitoring

    tolerations:
      - key: app
        value: monitoring
        operator: Equal

alertmanager:
  templateFiles:
    templates.tmpl: |-
      {{ define "chatapp.subject" }}
      [{{ .Status | toUpper }}][{{ .CommonLabels.severity | toUpper }}] {{ .CommonLabels.alertname }}
      {{ end }}

      {{ define "chatapp.text" }}

      ==================================================

      ChatApp Monitoring Alert

      ==================================================

      Status:
      {{ .Status }}

      Severity:
      {{ .CommonLabels.severity }}

      Component:
      {{ .CommonLabels.component }}

      Alert:
      {{ .CommonLabels.alertname }}

      Namespace:
      {{ .CommonLabels.namespace }}

      {{ range .Alerts }}

      Summary:
      {{ .Annotations.summary }}

      Description:
      {{ .Annotations.description }}

      Started:
      {{ .StartsAt }}

      {{ end }}

      ==================================================

      Generated by ChatApp Monitoring

      ==================================================

      {{ end }}

  alertmanagerSpec:
    alertmanagerConfigMatcherStrategy:
      type: None
      
    nodeSelector:
      app: monitoring

    tolerations:
      - key: app
        value: monitoring
        operator: Equal

prometheusOperator:
  tolerations:
    - operator: Exists

  admissionWebhooks:
    patch:
      tolerations:
        - operator: Exists

    create:
      tolerations:
        - operator: Exists

kube-state-metrics:
  rbac:
    create: true

  tolerations:
    - operator: Exists

prometheus-node-exporter:
  tolerations:
    - operator: Exists