global:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

controller:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

server:
  service: # new
      type: NodePort
      nodePortHttp: 30081
      nodePortHttps: 30444

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

repoServer:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

applicationSet:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

redis:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule