apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: chatapp-kubernetes-health-recording-rules
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: chatapp.kubernetes.health
      interval: 30s

      rules:
        - record: chatapp:deployment_unavailable_replicas
          expr: |
            sum by (namespace, deployment) (
              kube_deployment_status_replicas_unavailable
            )

        - record: chatapp:statefulset_desired_replicas
          expr: |
            kube_statefulset_replicas

        - record: chatapp:statefulset_ready_replicas
          expr: |
            kube_statefulset_status_replicas_ready

        - record: chatapp:statefulset_not_ready_replicas
          expr: |
            kube_statefulset_replicas
            -
            kube_statefulset_status_replicas_ready