apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allow-controller-to-aws.yaml
  - allow-controller-to-kubeapi.yaml
  - allow-webhook-to-kubeapi.yaml
  - allow-cert-controller-to-kubeapi.yaml