apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-ingress.yaml
  - argocd-deny-ingress.yaml
  - grafana-ingress.yaml
  - grafana-deny-ingress.yaml
  - prometheus-ingress.yaml
  - prometheus-deny-ingress.yaml