apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongodb-exporter

  template:
    metadata:
      labels:
        app: mongodb-exporter

    spec:
      tolerations:
            - key: "app"
              operator: "Equal"
              value: "db"
              effect: "NoSchedule"
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.47.2
          imagePullPolicy: IfNotPresent

          args:
            - --collect-all
            - --compatible-mode

          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-root
                  key: connectionString.standard

          ports:
            - name: metrics
              containerPort: 9216
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 20
            periodSeconds: 20

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi