name: Backend Prod DockerImage Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:
    inputs:
      node_version:
        type: number
        description: "Node.js version"
        required: false
        default: 20

jobs:
    set_default_node:
        if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        outputs:
            NODE_DEFAULT_VERSION: ${{ steps.set-node.outputs.NODE_DEFAULT_VERSION }}
        steps:
            - name: Set default Name
              id: set-node
              run: |
                echo "NODE_DEFAULT_VERSION=20" >> $GITHUB_OUTPUT
    test:
        needs: set_default_node
        uses: rajarshigit2441139/full-stack_chatApp/.github/workflows/backend_test.yml@main
        secrets: inherit
        with:
            node_version: ${{inputs.node_version || needs.set_default_node.outputs.NODE_DEFAULT_VERSION }}

    version:
        needs: [test, set_default_node]
        if: success() 
        uses: rajarshigit2441139/full-stack_chatApp/.github/workflows/semantic-version-release.yml@main
        secrets: inherit
        with:
            node_version: ${{inputs.node_version || needs.set_default_node.outputs.NODE_DEFAULT_VERSION }}

            app_path: backend

    prod_release:
        needs: [version, set_default_node]
        if: needs.version.outputs.released == 'true'
        uses: rajarshigit2441139/full-stack_chatApp/.github/workflows/backend_docker_build.yml@main
        secrets: inherit
        with:
            version: ${{ needs.version.outputs.current_version }}
            node_version: ${{ inputs.node_version || needs.set_default_node.outputs.NODE_DEFAULT_VERSION }}

