name: Backend Test

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend_test.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend_test.yml"
  workflow_call:
    inputs:
      node_version:
        type: number
        description: "Node.js version"
        required: false
        default: 24


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ inputs.node_version }}
            cache: "npm"
            cache-dependency-path: backend/package-lock.json

        - name: Install dependencies
          working-directory: backend
          run: |
            npm ci

        - name: Run tests with coverage
          working-directory: backend
          run: |
            npm run test:coverage

        - name: Upload coverage report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: backend-coverage
            path: backend/coverage/
            retention-days: 2