name: semantic-version-release

on:
  workflow_call:
    inputs:
      node_version:
        type: number
        description: "Node.js version"
        required: false
        default: 24
      app_path:
        type: string
        required: true

    outputs:
      current_version:
        description: "Released version"
        value: ${{ jobs.release.outputs.version }}
      released: 
        description: true/false
        value: ${{ jobs.release.outputs.released }}

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      released: ${{ steps.get_version.outputs.released }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      
      - name: Sync package-lock.json
        working-directory: ${{ inputs.app_path }}
        run: npm install --package-lock-only

      - name: Install dependencies
        working-directory: ${{ inputs.app_path }}
        run: npm ci

      - name: Get previous tag
        id: prev_tag
        run: |
          PREFIX="${{ inputs.app_path }}-v"
          TAG=$(git tag --list "${PREFIX}*" --sort=-v:refname | head -n 1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "prev-tag=$TAG"

      - name: Run semantic-release
        working-directory: ${{ inputs.app_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${{ github.event_name == 'pull_request' && format('refs/heads/{0}', github.event.pull_request.base.ref) || github.ref }}
          GITHUB_EVENT_NAME: ${{ github.event_name == 'pull_request' && 'push' || github.event_name }}
        run: |
          npx semantic-release || true

      - name: Get released version
        id: get_version
        run: |
          PREFIX="${{ inputs.app_path }}-v"

          PREV="${{ steps.prev_tag.outputs.tag }}"
          NEW=$(git tag --list "${PREFIX}*" --sort=-v:refname | head -n 1)

          released=false
          version=""

          if [ -n "$NEW" ]; then
            version="$NEW"
            if [ "$PREV" != "$NEW" ]; then
              released=true
            fi
          fi

          echo "released=$released" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

          echo "released=$released"
          echo "version=$version"
